### ISSUE TITLE
CSV output of changes in graph output values

### ISSUE THREAD

**Issue by y503unavailable** [matobaa/redmine_numericfield_chart_macro#1]
In order to handle changes in custom field values as data, 
it is necessary to directly operate with SQL statements inside Redmine.

**Comment by matobaa** [comment]
see https://github.com/matobaa/redmine_numericfield_chart_macro/compare/task/1
If it looks good to you please make me know

**Comment by y503unavailable** [comment]
LGTM
Thanks for your quick reply.
This feature allows Redmine to store and use time-series data that was previously unsupported.
